---
title: "Introduccion"
author: "Josefa Silva"
output: html_document
---

Cada vez surgen más casos de dopaje o presunto dopaje entre deportistas conocidos, los cuales saltan cada vez con más frecuencia a las portadas de los medios de comunicación. El dopaje es una vergüenza para el deporte, el cual es dificil de erradicar, es una práctica poca ética y muy peligrosa para la salud de los deportistas.

A finales del 2019, la Agencia Mundial Antidopaje (AMA) prohibe la participación de atletas rusos en competiciones deportivas tras conocerse un escándalo de dopaje en 2014. Teniendo en cuenta el tiempo en que se tardó en ver la luz dicho escandalo, nos hace plantearnos la siguiente pregunta. ¿Qué sucedió entre los 5 años que se demoró en salir a la luz dicho caso? ¿Qué otros países se encontraban involucrados? y la pregunta más importante, ¿Cual fue el motivo por el cual Rusia optó por dopar a sus deportistas?

Para responder dichas preguntas, primero realizaremos una comparación entre 2014 hasta 2018 para relaizar un contraste con la cantidad de casos. Teniendo en cuenta los países, deportes y género. Posteriormente nos iremos a un lado más politico para poder entender las razones del país Ruso y por último resumiremos lo explicado durante este informe


